server.port: 9001

logging.level.root: INFO
spring.data.mongodb.repositories.enabled: false

minio:
  url: http://localhost:9000
  accessKey: 7KEF5L0440Q9ZDM4YZBH
  secretKey: rPJMWCqeuuIKTmktINBKj9PD39luywmITqf/03wz
