server.port: 9001

logging.level.root: INFO
spring.data.mongodb.repositories.enabled: false

minio:
  url: http://localhost:9000
  accessKey: XKKFVGCNND21RLDCEFFI
  secretKey: 0B0VFZ28GvjQunfzC8jPQo1W1xr3YitYN+1SPXfC
